/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DrukarkiRouteImport } from './routes/drukarki'
import { Route as KasyFiskalneRouteImport } from './routes/kasy-fiskalne'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as SerwisRouteImport } from './routes/serwis'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminalePlatniczeRouteImport } from './routes/terminale-platnicze'
import { Route as DrukarkiIndexRouteImport } from './routes/drukarki/index'
import { Route as DrukarkiSlugRouteImport } from './routes/drukarki/$slug'
import { Route as KasyFiskalneIndexRouteImport } from './routes/kasy-fiskalne/index'
import { Route as KasyFiskalneSlugRouteImport } from './routes/kasy-fiskalne/$slug'
import { Route as TerminalePlatniczeIndexRouteImport } from './routes/terminale-platnicze/index'
import { Route as TerminalePlatniczeSlugRouteImport } from './routes/terminale-platnicze/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DrukarkiRoute = DrukarkiRouteImport.update({
  id: '/drukarki',
  path: '/drukarki',
  getParentRoute: () => rootRouteImport,
} as any)
const KasyFiskalneRoute = KasyFiskalneRouteImport.update({
  id: '/kasy-fiskalne',
  path: '/kasy-fiskalne',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const SerwisRoute = SerwisRouteImport.update({
  id: '/serwis',
  path: '/serwis',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalePlatniczeRoute = TerminalePlatniczeRouteImport.update({
  id: '/terminale-platnicze',
  path: '/terminale-platnicze',
  getParentRoute: () => rootRouteImport,
} as any)
const DrukarkiIndexRoute = DrukarkiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrukarkiRoute,
} as any)
const DrukarkiSlugRoute = DrukarkiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DrukarkiRoute,
} as any)
const KasyFiskalneIndexRoute = KasyFiskalneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KasyFiskalneRoute,
} as any)
const KasyFiskalneSlugRoute = KasyFiskalneSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KasyFiskalneRoute,
} as any)
const TerminalePlatniczeIndexRoute = TerminalePlatniczeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalePlatniczeRoute,
} as any)
const TerminalePlatniczeSlugRoute = TerminalePlatniczeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TerminalePlatniczeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/drukarki': typeof DrukarkiRouteWithChildren
  '/kasy-fiskalne': typeof KasyFiskalneRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/serwis': typeof SerwisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminale-platnicze': typeof TerminalePlatniczeRouteWithChildren
  '/drukarki/$slug': typeof DrukarkiSlugRoute
  '/kasy-fiskalne/$slug': typeof KasyFiskalneSlugRoute
  '/terminale-platnicze/$slug': typeof TerminalePlatniczeSlugRoute
  '/drukarki/': typeof DrukarkiIndexRoute
  '/kasy-fiskalne/': typeof KasyFiskalneIndexRoute
  '/terminale-platnicze/': typeof TerminalePlatniczeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kontakt': typeof KontaktRoute
  '/serwis': typeof SerwisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drukarki/$slug': typeof DrukarkiSlugRoute
  '/kasy-fiskalne/$slug': typeof KasyFiskalneSlugRoute
  '/terminale-platnicze/$slug': typeof TerminalePlatniczeSlugRoute
  '/drukarki': typeof DrukarkiIndexRoute
  '/kasy-fiskalne': typeof KasyFiskalneIndexRoute
  '/terminale-platnicze': typeof TerminalePlatniczeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/drukarki': typeof DrukarkiRouteWithChildren
  '/kasy-fiskalne': typeof KasyFiskalneRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/serwis': typeof SerwisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminale-platnicze': typeof TerminalePlatniczeRouteWithChildren
  '/drukarki/$slug': typeof DrukarkiSlugRoute
  '/kasy-fiskalne/$slug': typeof KasyFiskalneSlugRoute
  '/terminale-platnicze/$slug': typeof TerminalePlatniczeSlugRoute
  '/drukarki/': typeof DrukarkiIndexRoute
  '/kasy-fiskalne/': typeof KasyFiskalneIndexRoute
  '/terminale-platnicze/': typeof TerminalePlatniczeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/drukarki'
    | '/kasy-fiskalne'
    | '/kontakt'
    | '/serwis'
    | '/sitemap.xml'
    | '/terminale-platnicze'
    | '/drukarki/$slug'
    | '/kasy-fiskalne/$slug'
    | '/terminale-platnicze/$slug'
    | '/drukarki/'
    | '/kasy-fiskalne/'
    | '/terminale-platnicze/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kontakt'
    | '/serwis'
    | '/sitemap.xml'
    | '/drukarki/$slug'
    | '/kasy-fiskalne/$slug'
    | '/terminale-platnicze/$slug'
    | '/drukarki'
    | '/kasy-fiskalne'
    | '/terminale-platnicze'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/drukarki'
    | '/kasy-fiskalne'
    | '/kontakt'
    | '/serwis'
    | '/sitemap.xml'
    | '/terminale-platnicze'
    | '/drukarki/$slug'
    | '/kasy-fiskalne/$slug'
    | '/terminale-platnicze/$slug'
    | '/drukarki/'
    | '/kasy-fiskalne/'
    | '/terminale-platnicze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DrukarkiRoute: typeof DrukarkiRouteWithChildren
  KasyFiskalneRoute: typeof KasyFiskalneRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  SerwisRoute: typeof SerwisRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminalePlatniczeRoute: typeof TerminalePlatniczeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drukarki': {
      id: '/drukarki'
      path: '/drukarki'
      fullPath: '/drukarki'
      preLoaderRoute: typeof DrukarkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasy-fiskalne': {
      id: '/kasy-fiskalne'
      path: '/kasy-fiskalne'
      fullPath: '/kasy-fiskalne'
      preLoaderRoute: typeof KasyFiskalneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serwis': {
      id: '/serwis'
      path: '/serwis'
      fullPath: '/serwis'
      preLoaderRoute: typeof SerwisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminale-platnicze': {
      id: '/terminale-platnicze'
      path: '/terminale-platnicze'
      fullPath: '/terminale-platnicze'
      preLoaderRoute: typeof TerminalePlatniczeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drukarki/': {
      id: '/drukarki/'
      path: '/'
      fullPath: '/drukarki/'
      preLoaderRoute: typeof DrukarkiIndexRouteImport
      parentRoute: typeof DrukarkiRoute
    }
    '/drukarki/$slug': {
      id: '/drukarki/$slug'
      path: '/$slug'
      fullPath: '/drukarki/$slug'
      preLoaderRoute: typeof DrukarkiSlugRouteImport
      parentRoute: typeof DrukarkiRoute
    }
    '/kasy-fiskalne/': {
      id: '/kasy-fiskalne/'
      path: '/'
      fullPath: '/kasy-fiskalne/'
      preLoaderRoute: typeof KasyFiskalneIndexRouteImport
      parentRoute: typeof KasyFiskalneRoute
    }
    '/kasy-fiskalne/$slug': {
      id: '/kasy-fiskalne/$slug'
      path: '/$slug'
      fullPath: '/kasy-fiskalne/$slug'
      preLoaderRoute: typeof KasyFiskalneSlugRouteImport
      parentRoute: typeof KasyFiskalneRoute
    }
    '/terminale-platnicze/': {
      id: '/terminale-platnicze/'
      path: '/'
      fullPath: '/terminale-platnicze/'
      preLoaderRoute: typeof TerminalePlatniczeIndexRouteImport
      parentRoute: typeof TerminalePlatniczeRoute
    }
    '/terminale-platnicze/$slug': {
      id: '/terminale-platnicze/$slug'
      path: '/$slug'
      fullPath: '/terminale-platnicze/$slug'
      preLoaderRoute: typeof TerminalePlatniczeSlugRouteImport
      parentRoute: typeof TerminalePlatniczeRoute
    }
  }
}

interface DrukarkiRouteChildren {
  DrukarkiSlugRoute: typeof DrukarkiSlugRoute
  DrukarkiIndexRoute: typeof DrukarkiIndexRoute
}

const DrukarkiRouteChildren: DrukarkiRouteChildren = {
  DrukarkiSlugRoute: DrukarkiSlugRoute,
  DrukarkiIndexRoute: DrukarkiIndexRoute,
}

const DrukarkiRouteWithChildren = DrukarkiRoute._addFileChildren(
  DrukarkiRouteChildren,
)

interface KasyFiskalneRouteChildren {
  KasyFiskalneSlugRoute: typeof KasyFiskalneSlugRoute
  KasyFiskalneIndexRoute: typeof KasyFiskalneIndexRoute
}

const KasyFiskalneRouteChildren: KasyFiskalneRouteChildren = {
  KasyFiskalneSlugRoute: KasyFiskalneSlugRoute,
  KasyFiskalneIndexRoute: KasyFiskalneIndexRoute,
}

const KasyFiskalneRouteWithChildren = KasyFiskalneRoute._addFileChildren(
  KasyFiskalneRouteChildren,
)

interface TerminalePlatniczeRouteChildren {
  TerminalePlatniczeSlugRoute: typeof TerminalePlatniczeSlugRoute
  TerminalePlatniczeIndexRoute: typeof TerminalePlatniczeIndexRoute
}

const TerminalePlatniczeRouteChildren: TerminalePlatniczeRouteChildren = {
  TerminalePlatniczeSlugRoute: TerminalePlatniczeSlugRoute,
  TerminalePlatniczeIndexRoute: TerminalePlatniczeIndexRoute,
}

const TerminalePlatniczeRouteWithChildren =
  TerminalePlatniczeRoute._addFileChildren(TerminalePlatniczeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DrukarkiRoute: DrukarkiRouteWithChildren,
  KasyFiskalneRoute: KasyFiskalneRouteWithChildren,
  KontaktRoute: KontaktRoute,
  SerwisRoute: SerwisRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminalePlatniczeRoute: TerminalePlatniczeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
